[2024-04-26 08:04:27,922] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: json_file.step1_Decidewhichtask 2024-04-26T08:04:22.171039+00:00 [queued]>
[2024-04-26 08:04:27,946] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: json_file.step1_Decidewhichtask 2024-04-26T08:04:22.171039+00:00 [queued]>
[2024-04-26 08:04:27,947] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2024-04-26 08:04:27,948] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2024-04-26 08:04:27,949] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2024-04-26 08:04:27,977] {taskinstance.py:1089} INFO - Executing <Task(BranchPythonOperator): step1_Decidewhichtask> on 2024-04-26T08:04:22.171039+00:00
[2024-04-26 08:04:27,990] {standard_task_runner.py:52} INFO - Started process 153 to run task
[2024-04-26 08:04:28,002] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'json_file', 'step1_Decidewhichtask', '2024-04-26T08:04:22.171039+00:00', '--job-id', '14072', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/json_file.py', '--cfg-path', '/tmp/tmpikz_tc83', '--error-file', '/tmp/tmpinz2os87']
[2024-04-26 08:04:28,004] {standard_task_runner.py:77} INFO - Job 14072: Subtask step1_Decidewhichtask
[2024-04-26 08:04:28,060] {logging_mixin.py:104} INFO - Running <TaskInstance: json_file.step1_Decidewhichtask 2024-04-26T08:04:22.171039+00:00 [running]> on host c6f0c13ba6da
[2024-04-26 08:04:28,151] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=json_file
AIRFLOW_CTX_TASK_ID=step1_Decidewhichtask
AIRFLOW_CTX_EXECUTION_DATE=2024-04-26T08:04:22.171039+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-26T08:04:22.171039+00:00
[2024-04-26 08:04:28,158] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 324, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/json_file.py", line 34, in decideWhichTask
    stepint = int(stepint[1])
ValueError: invalid literal for int() with base 10: "1_BashCommand') "
[2024-04-26 08:04:28,163] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=json_file, task_id=step1_Decidewhichtask, execution_date=20240426T080422, start_date=20240426T080427, end_date=20240426T080428
[2024-04-26 08:04:28,219] {local_task_job.py:146} INFO - Task exited with return code 1
