[2024-04-26 07:51:06,600] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: json_file.step2_Decidewhichtask 2024-04-26T07:50:59.390908+00:00 [queued]>
[2024-04-26 07:51:06,618] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: json_file.step2_Decidewhichtask 2024-04-26T07:50:59.390908+00:00 [queued]>
[2024-04-26 07:51:06,619] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2024-04-26 07:51:06,619] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2024-04-26 07:51:06,619] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2024-04-26 07:51:06,646] {taskinstance.py:1089} INFO - Executing <Task(BranchPythonOperator): step2_Decidewhichtask> on 2024-04-26T07:50:59.390908+00:00
[2024-04-26 07:51:06,656] {standard_task_runner.py:52} INFO - Started process 91 to run task
[2024-04-26 07:51:06,664] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'json_file', 'step2_Decidewhichtask', '2024-04-26T07:50:59.390908+00:00', '--job-id', '14045', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/json_file.py', '--cfg-path', '/tmp/tmpu91eqhah', '--error-file', '/tmp/tmp0u8gbi60']
[2024-04-26 07:51:06,667] {standard_task_runner.py:77} INFO - Job 14045: Subtask step2_Decidewhichtask
[2024-04-26 07:51:06,765] {logging_mixin.py:104} INFO - Running <TaskInstance: json_file.step2_Decidewhichtask 2024-04-26T07:50:59.390908+00:00 [running]> on host c6f0c13ba6da
[2024-04-26 07:51:06,855] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=json_file
AIRFLOW_CTX_TASK_ID=step2_Decidewhichtask
AIRFLOW_CTX_EXECUTION_DATE=2024-04-26T07:50:59.390908+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-26T07:50:59.390908+00:00
[2024-04-26 07:51:06,857] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 324, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/json_file.py", line 35, in decideWhichTask
    stepint = int(stepint[1])
ValueError: invalid literal for int() with base 10: "2_BashCommand') }}"
[2024-04-26 07:51:06,873] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=json_file, task_id=step2_Decidewhichtask, execution_date=20240426T075059, start_date=20240426T075106, end_date=20240426T075106
[2024-04-26 07:51:06,970] {local_task_job.py:146} INFO - Task exited with return code 1
