[2024-04-30 16:10:06,655] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: json_file.step3_Decidewhichtask 2024-04-29T16:09:31.898112+00:00 [queued]>
[2024-04-30 16:10:06,868] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: json_file.step3_Decidewhichtask 2024-04-29T16:09:31.898112+00:00 [queued]>
[2024-04-30 16:10:06,885] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 16:10:06,886] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2024-04-30 16:10:06,899] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2024-04-30 16:10:06,951] {taskinstance.py:1089} INFO - Executing <Task(BranchPythonOperator): step3_Decidewhichtask> on 2024-04-29T16:09:31.898112+00:00
[2024-04-30 16:10:07,013] {standard_task_runner.py:52} INFO - Started process 89 to run task
[2024-04-30 16:10:07,052] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'json_file', 'step3_Decidewhichtask', '2024-04-29T16:09:31.898112+00:00', '--job-id', '14098', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/json_file.py', '--cfg-path', '/tmp/tmpukna4yxg', '--error-file', '/tmp/tmp_dayq4yz']
[2024-04-30 16:10:07,058] {standard_task_runner.py:77} INFO - Job 14098: Subtask step3_Decidewhichtask
[2024-04-30 16:10:07,278] {logging_mixin.py:104} INFO - Running <TaskInstance: json_file.step3_Decidewhichtask 2024-04-29T16:09:31.898112+00:00 [running]> on host c6f0c13ba6da
[2024-04-30 16:10:07,553] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=json_file
AIRFLOW_CTX_TASK_ID=step3_Decidewhichtask
AIRFLOW_CTX_EXECUTION_DATE=2024-04-29T16:09:31.898112+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-29T16:09:31.898112+00:00
[2024-04-30 16:10:07,594] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 324, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/json_file.py", line 35, in decideWhichTask
    stepint = int(stepint[1])
UnboundLocalError: local variable 'stepint' referenced before assignment
[2024-04-30 16:10:07,613] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=json_file, task_id=step3_Decidewhichtask, execution_date=20240429T160931, start_date=20240430T161006, end_date=20240430T161007
[2024-04-30 16:10:07,708] {local_task_job.py:146} INFO - Task exited with return code 1
