[2024-04-26 08:03:04,261] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: json_file.step2_Decidewhichtask 2024-04-26T08:03:00.159028+00:00 [queued]>
[2024-04-26 08:03:04,273] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: json_file.step2_Decidewhichtask 2024-04-26T08:03:00.159028+00:00 [queued]>
[2024-04-26 08:03:04,274] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2024-04-26 08:03:04,274] {taskinstance.py:1069} INFO - Starting attempt 1 of 1
[2024-04-26 08:03:04,275] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2024-04-26 08:03:04,290] {taskinstance.py:1089} INFO - Executing <Task(BranchPythonOperator): step2_Decidewhichtask> on 2024-04-26T08:03:00.159028+00:00
[2024-04-26 08:03:04,295] {standard_task_runner.py:52} INFO - Started process 133 to run task
[2024-04-26 08:03:04,299] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'json_file', 'step2_Decidewhichtask', '2024-04-26T08:03:00.159028+00:00', '--job-id', '14063', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/json_file.py', '--cfg-path', '/tmp/tmpd_j1idrt', '--error-file', '/tmp/tmpjm8q44yn']
[2024-04-26 08:03:04,300] {standard_task_runner.py:77} INFO - Job 14063: Subtask step2_Decidewhichtask
[2024-04-26 08:03:04,342] {logging_mixin.py:104} INFO - Running <TaskInstance: json_file.step2_Decidewhichtask 2024-04-26T08:03:00.159028+00:00 [running]> on host c6f0c13ba6da
[2024-04-26 08:03:04,382] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=json_file
AIRFLOW_CTX_TASK_ID=step2_Decidewhichtask
AIRFLOW_CTX_EXECUTION_DATE=2024-04-26T08:03:00.159028+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-26T08:03:00.159028+00:00
[2024-04-26 08:03:04,383] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 324, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/json_file.py", line 34, in decideWhichTask
    stepint = int(stepint[1])
ValueError: invalid literal for int() with base 10: "2_BashCommand') }"
[2024-04-26 08:03:04,388] {taskinstance.py:1532} INFO - Marking task as FAILED. dag_id=json_file, task_id=step2_Decidewhichtask, execution_date=20240426T080300, start_date=20240426T080304, end_date=20240426T080304
[2024-04-26 08:03:04,434] {local_task_job.py:146} INFO - Task exited with return code 1
